### ISSUE TITLE
Parse Error at install

### ISSUE THREAD

**Issue by AdrieanKhisbe** [zulu-zsh/zulu#104]
While trying to install I get the following error:
```
/Users/abecchis/.zulu/core/zulu
/Users/abecchis/.zulu/core/zulu:2355: parse error near `>&'
/Users/abecchis/.zshrc:335: command not found: zulu
```
```
zsh --version
zsh 5.1.1 (x86_64-apple-darwin15.0.0)
```

**Comment by AdrieanKhisbe** [comment]
Digging I think I found the cause. I made a Pr for that :)

**Comment by molovo** [comment]
A few quick questions to help me with debugging, and to track down if the issue is in Zulu or the install script:

1. Did you specify a custom `$ZULU_DIR` or `$ZULU_CONFIG_DIR`?
2. If yes, does the error still occur if you use the defaults?
3. After receiving the error, does Zulu work if you do the following steps:

```
cd ~/.zulu/core
./build.zsh
source zulu
zulu
```

**Comment by AdrieanKhisbe** [comment]
1. No
2. No to 1.
3. Going to try

**Comment by AdrieanKhisbe** [comment]
3. Doesnt work :/

**Comment by molovo** [comment]
Ok, that rules out any errors in the install script, I think.

**Comment by AdrieanKhisbe** [comment]
Yep sure.

**Comment by AdrieanKhisbe** [comment]
hello @molovo :)
did you have time to dig on the issue?
