### ISSUE TITLE
Index packages

### ISSUE THREAD

**Issue by rolling-space** [zulu-zsh/zulu#32]
Hi @molovo,

I have created some plugins (`zulu-` prefixed) and published them under my `github` account. If you wanna have a look and decide that they can make it to the official `zulu` distro, let me know and I will prepare them accordingly (documentation, comments etc). I keep their respective index files locally though, happy to provide them in any case.

Cheers!

**Comment by molovo** [comment]
@rolling-space that's some great work, thanks for that. I'm happy to include all of those - if you could create a pull request on the [index](https://github.com/zulu-zsh/index) repo containing all of those I'll happily accept it. If you could keep it to one package per commit all bundled into the same PR that would be great, just in case we need to revert one of them. Also, could you please leave the `zulu-` prefix off of the package names when you create the index files for them - it makes the packages easier to install etc. without it.

One question: how different is your git plugin compared to the [currently included one](https://github.com/zulu-zsh/plugin-git)? If you've made some improvements, it would be great if you could submit a PR with them there, rather than creating a new package with the same functionality.

Thanks again for some great work!

**Comment by rolling-space** [comment]
My pleasure to contribute @molovo, really! 

I used my git plugin (which is taken as-is from `zim`) directly, but find the differences in the attached -- it is html, renamed it as `txt` to fit github's requirements). You may want to have a closer look at the `log` section by the way.
[mygit-vs-zulugit.html.txt](https://github.com/zulu-zsh/zulu/files/714733/mygit-vs-zulugit.html.txt)

**Comment by rolling-space** [comment]
@molovo, you can expect the first batch during the weekend...

**Comment by molovo** [comment]
Yeah those git plugin changes look great, if you want to submit those as well, I'll happily include them. Thanks!

**Comment by molovo** [comment]
@rolling-space Thanks very much for those PRs, a great contribution. Closing this now, as they've all been merged.
