### ISSUE TITLE
Initialization and loading documentation

### ISSUE THREAD

**Issue by Tuurlijk** [zulu-zsh/zulu#86]
I would like to know how the loading and initialization of packages and functions work. Is there any documentation on that?

**Comment by molovo** [comment]
@Tuurlijk there's no documentation at the moment, but I'll give you a quick rundown. Be warned, it does a lot.

First of all, each package in the index can define three types of files.

* `init` files are symlinked to `~/.zulu/init`, and are sourced on terminal startup
* `share` files are symlinked to `~/.zulu/share`, which is in `$fpath`. Used for auto-loadable functions and completion files
* `bin` files are symlinked to `~/.zulu/bin`, which is in `$path`. Used for executable scripts

Then, when `zulu init` is called, it goes through the following steps:

1. Check for the `--dev` flag, and turn on dev mode if it is set. This re-loads the source for each command when it is run, rather than using the compiled source, so that Zulu does not need to be built between changes.
2. Check for the `--next` flag, and switch the Zulu core repository to the correct branch (`master` or `next`). This step is skipped when the `--dev` flag is passed
3. Set the contents of `$path`, `$fpath`, `$cdpath` and `$manpath`
4. Set up keyboard input and some keybindings
5. Set up completion
6. Load all packages by sourcing each file in `~/.zulu/init`
7. Set up history
8. Load aliases
9. Load functions
10. Load environment variables
11. Load the theme
12. Compile the following files:
    * Zulu itself (`~/.zulu/core/zulu`)
    * Everything in `~/.zulu/init`, `~/.zulu/share`, `~/.zulu/bin`
    * The completion dump (`~/.zcomp*`)
    * `~/.zshenv`
    * `~/.zlogin`
    * `~/.zprofile`
    * `~/.zshrc`
    * `~/.zlogout`
13. If the `--check-for-update` flag is passed, check for updates and report any to the user

That should cover everything. If you have any more questions, let me know!
